debug:
  false
server:
  port:
    8004
  error:
    path:
      /error
    whitelabel:
      enabled:
        false
spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
      
elasticsearch:
  host: 10.53.34.28
  port: 9200
  username: AI-297397
  password: XU1g0WFhcAaNKRvKZjq3

feign:
  client:
    config:
      appsearch:
        defaultRequestHeaders:
          Authorization:"Bearer search-untdq4d62zdka9zq4mkre4vv""